## 2. The Series Object — In Depth

In [74]:
import pandas as pd
import numpy as np
s1=pd.Series(range(10,30,2))
print(s1)
print(type(s1))

0    10
1    12
2    14
3    16
4    18
5    20
6    22
7    24
8    26
9    28
dtype: int64
<class 'pandas.Series'>

In [2]:
s2=pd.Series(range(10,50,10),index=['a', 'b', 'c', 'd'],name="myseries")
print(s2)

a    10
b    20
c    30
d    40
Name: myseries, dtype: int64

In [3]:
s5 = pd.Series(0.0, index=['a', 'b', 'c', 'd', 'e'])
print(s5)
dir(s5)

a    0.0
b    0.0
c    0.0
d    0.0
e    0.0
dtype: float64

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'a',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'b',
 'between',
 'between_time',
 'bfill',
 'c',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'd',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'e',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

### 2.2 Key attributes of a Series

In [4]:
s = pd.Series([10, 20, 30, 40, 50,],
            #   index=['a', 'b', 'c', 'd', 'e'],
              name='measurements')

print(f"values  : {s.values}          # underlying NumPy array")
print(f"index   : {list(s.index)}")
print(f"name    : {s.name}")
print(f"dtype   : {s.dtype}            # data type of values")
print(f"size    : {s.size}             # total number of elements")
print(f"shape   : {s.shape}            # (length,) tuple")
print(f"ndim    : {s.ndim}             # always 1 for a Series")

values  : [10 20 30 40 50]          # underlying NumPy array
index   : [0, 1, 2, 3, 4]
name    : measurements
dtype   : int64            # data type of values
size    : 5             # total number of elements
shape   : (5,)            # (length,) tuple
ndim    : 1             # always 1 for a Series

In [5]:
print(s[1:4]) #Not recommended in pandas
print(s.iloc[1:4])# Use this instead of the upper

1    20
2    30
3    40
Name: measurements, dtype: int64
1    20
2    30
3    40
Name: measurements, dtype: int64

### 2.4 Vectorized operations on a Series

Series operations are **vectorized** — applied to every element at once. This is far faster than a Python loop.

In [6]:
prices=pd.Series([100, 250, 75, 400, 150],name='price')
print("With 8% tax:")
print((prices*1.08).round(2))
# Element-wise comparison
print("Expensive items (>200):")
print(prices>200)

With 8% tax:
0    108.0
1    270.0
2     81.0
3    432.0
4    162.0
Name: price, dtype: float64
Expensive items (>200):
0    False
1     True
2    False
3     True
4    False
Name: price, dtype: bool

## 3. The DataFrame Object — In Depth

### 3.1 Creating DataFrames — every way

In [7]:
df1=pd.DataFrame({
   'name': ['Alice', 'Bob', 'Carol', 'Dan'],
    'age': [25, 30, 35, 40],
    'city': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bhaktapur'],
    'salary': [50000, 60000, 75000, 90000]
})
df1

    name  age       city  salary
0  Alice   25  Kathmandu   50000
1    Bob   30    Pokhara   60000
2  Carol   35   Lalitpur   75000
3    Dan   40  Bhaktapur   90000

In [8]:
records = [
    {'name': 'Alice', 'age': 25, 'city': 'Kathmandu'},
    {'name': 'Bob', 'age': 30, 'city': 'Pokhara'},
    {'name': 'Carol', 'age': 35},                    # missing 'city' → NaN
]
df2=pd.DataFrame(records)
df2

    name  age       city
0  Alice   25  Kathmandu
1    Bob   30    Pokhara
2  Carol   35        NaN

In [9]:
data = [
    ['Alice', 25, 'Kathmandu'],
    ['Bob', 30, 'Pokhara'],
    ['Carol', 35, 'Lalitpur'],
]
df3=pd.DataFrame(data,columns=['name','age','city'])
df3

    name  age       city
0  Alice   25  Kathmandu
1    Bob   30    Pokhara
2  Carol   35   Lalitpur

In [10]:
my_data=pd.read_excel("sales_data.xlsx")
my_data

         Date   Product     Category  Quantity UnitPrice TotalRevenue
0  2026-01-15    Laptop  Electronics         5   $800.00    $4,000.00
1  2026-01-16     Mouse  Accessories        25    $25.00      $625.00
2  2026-01-17  Keyboard  Accessories        15    $45.00      $675.00
3  2026-01-18   Monitor  Electronics         8   $250.00    $2,000.00
4  2026-01-19   Headset  Accessories        12    $75.00      $900.00

In [11]:
my_data=pd.read_csv("subset.csv",sep=",",header=0)
my_data

    survived  pclass     sex   age      fare
0          0       3    male  22.0    7.2500
1          1       1  female  38.0   71.2833
2          1       3  female  26.0    7.9250
3          1       1  female  35.0   53.1000
4          0       3    male  35.0    8.0500
5          0       3    male   NaN    8.4583
6          0       1    male  54.0   51.8625
7          0       3    male   2.0   21.0750
8          1       3  female  27.0   11.1333
9          1       2  female  14.0   30.0708
10         1       3  female   4.0   16.7000
11         1       1  female  58.0   26.5500
12         0       3    male  20.0    8.0500
13         0       3    male  39.0   31.2750
14         0       3  female  14.0    7.8542
15         1       2  female  55.0   16.0000
16         0       3    male   2.0   29.1250
17         1       2    male   NaN   13.0000
18         0       3  female  31.0   18.0000
19         1       3  female   NaN    7.2250
20         0       2    male  35.0   26.0000
21         1       2    male  34.0   13.0000
22         1       3  female  15.0    8.0292
23         1       1    male  28.0   35.5000
24         0       3  female   8.0   21.0750
25         1       3  female  38.0   31.3875
26         0       3    male   NaN    7.2250
27         0       1    male  19.0  263.0000
28         1       3  female   NaN    7.8792
29         0       3    male   NaN    7.8958
30         0       1    male  40.0   27.7208
31         1       1  female   NaN  146.5208
32         1       3  female   NaN    7.7500
33         0       2    male  66.0   10.5000
34         0       1    male  28.0   82.1708
35         0       1    male  42.0   52.0000
36         1       3    male   NaN    7.2292
37         0       3    male  21.0    8.0500
38         0       3  female  18.0   18.0000
39         1       3  female  14.0   11.2417
40         0       3  female  40.0    9.4750
41         0       2  female  27.0   21.0000
42         0       3    male   NaN    7.8958
43         1       2  female   3.0   41.5792
44         1       3  female  19.0    7.8792
45         0       3    male   NaN    8.0500
46         0       3    male   NaN   15.5000
47         1       3  female   NaN    7.7500
48         0       3    male   NaN   21.6792
49         0       3  female  18.0   17.8000

In [12]:
df_subset=pd.read_csv(
    'titanic.csv',
    usecols=['survived', 'pclass', 'sex', 'age', 'fare'],
    dtype={'pclass': 'category'},
    na_values=['?', 'unknown'],
    nrows=50
    )
df_subset

    survived pclass     sex   age      fare
0          0      3    male  22.0    7.2500
1          1      1  female  38.0   71.2833
2          1      3  female  26.0    7.9250
3          1      1  female  35.0   53.1000
4          0      3    male  35.0    8.0500
5          0      3    male   NaN    8.4583
6          0      1    male  54.0   51.8625
7          0      3    male   2.0   21.0750
8          1      3  female  27.0   11.1333
9          1      2  female  14.0   30.0708
10         1      3  female   4.0   16.7000
11         1      1  female  58.0   26.5500
12         0      3    male  20.0    8.0500
13         0      3    male  39.0   31.2750
14         0      3  female  14.0    7.8542
15         1      2  female  55.0   16.0000
16         0      3    male   2.0   29.1250
17         1      2     NaN   NaN   13.0000
18         0      3     NaN  31.0   18.0000
19         1      3     NaN   NaN    7.2250
20         0      2     NaN  35.0   26.0000
21         1      2     NaN  34.0   13.0000
22         1      3     NaN  15.0    8.0292
23         1      1     NaN  28.0   35.5000
24         0      3     NaN   8.0   21.0750
25         1      3     NaN  38.0   31.3875
26         0      3     NaN   NaN    7.2250
27         0      1     NaN  19.0  263.0000
28         1      3     NaN   NaN    7.8792
29         0      3     NaN   NaN    7.8958
30         0      1     NaN  40.0   27.7208
31         1      1     NaN   NaN       NaN
32         1      3     NaN   NaN       NaN
33         0      2     NaN  66.0       NaN
34         0      1     NaN  28.0       NaN
35         0      1     NaN  42.0       NaN
36         1      3     NaN   NaN       NaN
37         0      3     NaN  21.0       NaN
38         0      3     NaN  18.0       NaN
39         1      3     NaN  14.0       NaN
40         0      3     NaN  40.0       NaN
41         0      2     NaN  27.0       NaN
42         0      3     NaN   NaN       NaN
43         1      2     NaN   3.0       NaN
44         1      3     NaN  19.0       NaN
45         0      3     NaN   NaN       NaN
46         0      3     NaN   NaN       NaN
47         1      3     NaN   NaN       NaN
48         0      3     NaN   NaN       NaN
49         0      3     NaN  18.0       NaN

In [13]:
df_subset.to_csv("subset.csv",index=False)

In [14]:
df=pd.read_csv('titanic.csv')
len(df)

891

In [15]:
df.head(5)

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,"Carter, Miss. Sarah",1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,"Fitzgerald, Miss. Hannah",1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,"Harris, Miss. Florence",1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,"White, Mr. Harold",0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [16]:
df.tail(3) ### last 3 rows

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
888,"White, Mrs. Hannah",0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,"Harris, Mr. Joseph",1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,"Allen, Mr. Harold",0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [17]:
df.sample(5,random_state=42)

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
709,"Young, Mr. Patrick",1,3,male,NaN,1,1,15.2458,C,Third,man,True,NaN,Cherbourg,yes,False
439,"Stewart, Mr. Charles",0,2,male,31.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
840,"Brown, Mr. Charles",0,3,male,20.0,0,0,7.9250,S,Third,man,True,NaN,Southampton,no,True
720,"Nelson, Miss. Alice",1,2,female,6.0,0,1,33.0000,S,Second,child,False,NaN,Southampton,yes,False
39,"Gordon, Miss. Edith",1,3,NaN,14.0,1,0,NaN,C,Third,child,False,NaN,Cherbourg,yes,False

In [18]:
len(list(df.columns))

16

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         891 non-null    str
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   sex          852 non-null    str
 4   age          714 non-null    float64
 5   sibsp        891 non-null    int64
 6   parch        891 non-null    int64
 7   fare         852 non-null    float64
 8   embarked     889 non-null    str
 9   class        891 non-null    str
 10  who          891 non-null    str
 11  adult_male   891 non-null    bool
 12  deck         203 non-null    str
 13  embark_town  889 non-null    str
 14  alive        891 non-null    str
 15  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(8)
memory usage: 140.0 KB

In [20]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  852.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.365008
std      0.486592    0.836071   14.526497    1.102743    0.806057   50.406742
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.895800
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [21]:
df.describe(include='object')

C:\Users\user\AppData\Local\Temp\ipykernel_4956\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

                      name   sex embarked  class  who deck  embark_town alive
count                  891   852      889    891  891  203          889   891
unique                 616     2        3      3    3    7            3     2
top     Davies, Mr. Arthur  male        S  Third  man    C  Southampton    no
freq                     5   556      644    491  537   59          644   549

In [22]:
df.describe(include='all')

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891,891.000000,891.000000,852,714.000000,891.000000,891.000000,852.000000,889,891,891,891,203,889,891,891
unique,616,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,"Davies, Mr. Arthur",NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,5,NaN,NaN,556,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,NaN,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.365008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,50.406742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.895800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df.dtypes

name               str
survived         int64
pclass           int64
sex                str
age            float64
sibsp            int64
parch            int64
fare           float64
embarked           str
class              str
who                str
adult_male        bool
deck               str
embark_town        str
alive              str
alone             bool
dtype: object

In [24]:
df.nunique().sort_values(ascending=False)

name           616
fare           243
age             88
sibsp            7
parch            7
deck             7
embarked         3
pclass           3
embark_town      3
class            3
who              3
sex              2
survived         2
adult_male       2
alive            2
alone            2
dtype: int64

In [25]:
df['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [26]:
df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [27]:
df['embarked'].value_counts(dropna=False)

embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [28]:
df.isna()

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [29]:
df.isna().sum()

name             0
survived         0
pclass           0
sex             39
age            177
sibsp            0
parch            0
fare            39
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [30]:
df['age'].head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: age, dtype: float64

In [31]:
df[['name','age']].tail(20)

                        name   age
871       Davies, Mrs. Emily  47.0
872      Thompson, Mr. Henry  33.0
873    Phillips, Mr. William  47.0
874      Nelson, Miss. Helen  28.0
875       Harris, Miss. Ruth  15.0
876        Allen, Mr. Arthur  20.0
877         Nelson, Mr. John  19.0
878        Brown, Mr. Joseph   NaN
879       Wilson, Mrs. Helen  56.0
880         Kelly, Mrs. Mary  25.0
881        Smith, Mr. Edward  33.0
882   Fitzgerald, Miss. Mary  22.0
883  Fitzgerald, Mr. William  28.0
884     Stewart, Mr. William  25.0
885        White, Mrs. Alice  39.0
886       White, Mr. William  27.0
887     Roberts, Miss. Edith  19.0
888       White, Mrs. Hannah   NaN
889       Harris, Mr. Joseph  26.0
890        Allen, Mr. Harold  32.0

In [32]:
df.loc[0]

name           Kelly, Mr. Patrick
survived                        0
pclass                          3
sex                          male
age                          22.0
sibsp                           1
parch                           0
fare                         7.25
embarked                        S
class                       Third
who                           man
adult_male                   True
deck                          NaN
embark_town           Southampton
alive                          no
alone                       False
Name: 0, dtype: object

In [33]:
df.loc[[0,3,5,6,9]]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
3,"Harris, Miss. Florence",1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
5,"Andrews, Mr. Harold",0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,"Harris, Mr. Robert",0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
9,"Davis, Miss. Emily",1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [34]:
df.loc[0:10:2]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,"Fitzgerald, Miss. Hannah",1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,"White, Mr. Harold",0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,"Harris, Mr. Robert",0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
8,"Andrews, Mrs. Alice",1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,"Gordon, Miss. Hannah",1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False

In [35]:
df.iloc[0:5] ## INDEX BASED LOCATION

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,"Carter, Miss. Sarah",1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,"Fitzgerald, Miss. Hannah",1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,"Harris, Miss. Florence",1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,"White, Mr. Harold",0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [36]:
df.iloc[5:15,0:6]## ROWS AND COLUMN BOTH

                       name  survived  pclass     sex   age  sibsp
5       Andrews, Mr. Harold         0       3    male   NaN      0
6        Harris, Mr. Robert         0       1    male  54.0      0
7   Nelson, Master. Charles         0       3    male   2.0      3
8       Andrews, Mrs. Alice         1       3  female  27.0      0
9        Davis, Miss. Emily         1       2  female  14.0      1
10     Gordon, Miss. Hannah         1       3  female   4.0      1
11     Thompson, Miss. Mary         1       1  female  58.0      0
12        Jones, Mr. Joseph         0       3    male  20.0      0
13          Quinn, Mr. John         0       3    male  39.0      1
14    Jones, Miss. Florence         0       3  female  14.0      0

In [37]:
df.iloc[-1:-50:-2]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,"Allen, Mr. Harold",0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
888,"White, Mrs. Hannah",0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
886,"White, Mr. William",0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
884,"Stewart, Mr. William",0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
882,"Fitzgerald, Miss. Mary",0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
880,"Kelly, Mrs. Mary",1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
878,"Brown, Mr. Joseph",0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
876,"Allen, Mr. Arthur",0,3,male,20.0,0,0,9.8458,S,Third,man,True,NaN,Southampton,no,True
874,"Nelson, Miss. Helen",1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
872,"Thompson, Mr. Henry",0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
870,"Wilson, Mr. Harold",0,3,male,26.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
868,"Roberts, Mr. William",0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
866,"Davies, Miss. Sarah",1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False
864,"Gordon, Mr. Samuel",0,2,male,24.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
862,"Wilson, Miss. Bridget",1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
860,"Phillips, Mr. Joseph",0,3,male,41.0,2,0,14.1083,S,Third,man,True,NaN,Southampton,no,False
858,"Davis, Mrs. Mary",1,3,female,24.0,0,3,19.2583,C,Third,woman,False,NaN,Cherbourg,yes,False
856,"Nelson, Mrs. Elizabeth",1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
854,"Fitzgerald, Miss. Bridget",0,2,female,44.0,1,0,26.0000,S,Second,woman,False,NaN,Southampton,no,False
852,"Clark, Miss. Emily",0,3,female,9.0,1,1,15.2458,C,Third,child,False,NaN,Cherbourg,no,False
850,"Bird, Master. John",0,3,male,4.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
848,"O'Brien, Mr. Harold",0,2,male,28.0,0,1,33.0000,S,Second,man,True,NaN,Southampton,no,False
846,"Young, Mr. Frank",0,3,male,NaN,8,2,69.5500,S,Third,man,True,NaN,Southampton,no,False
844,"Carter, Mr. Charles",0,3,male,17.0,0,0,8.6625,S,Third,man,True,NaN,Southampton,no,True
842,"Bird, Miss. Margaret",1,1,female,30.0,0,0,31.0000,C,First,woman,False,NaN,Cherbourg,yes,True

In [38]:
df.iloc[-1:-30:-2,-1:-5:-1]

     alone alive  embark_town deck
890   True    no   Queenstown  NaN
888  False    no  Southampton  NaN
886   True    no  Southampton  NaN
884   True    no  Southampton  NaN
882   True    no  Southampton  NaN
880  False   yes  Southampton  NaN
878   True    no  Southampton  NaN
876   True    no  Southampton  NaN
874  False   yes    Cherbourg  NaN
872   True    no  Southampton    B
870   True    no  Southampton  NaN
868   True    no  Southampton  NaN
866  False   yes    Cherbourg  NaN
864   True    no  Southampton  NaN
862   True   yes  Southampton    D

In [39]:
### FILTERING
condition=df['age']>60
df[condition]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
33,"Stewart, Mr. Edward",0,2,NaN,66.0,0,0,NaN,S,Second,man,True,NaN,Southampton,no,True
54,"Nelson, Mr. Henry",0,1,NaN,65.0,0,1,NaN,C,First,man,True,B,Cherbourg,no,False
96,"Stewart, Mr. Samuel",0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,"Taylor, Mr. Joseph",0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
170,"White, Mr. Edward",0,1,male,61.0,0,0,33.5000,S,First,man,True,B,Southampton,no,True
252,"Wilson, Mr. Harold",0,1,male,62.0,0,0,26.5500,S,First,man,True,C,Southampton,no,True
275,"Young, Miss. Bertha",1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
280,"Carter, Mr. Robert",0,3,male,65.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
326,"Thompson, Mr. Walter",0,3,male,61.0,0,0,6.2375,S,Third,man,True,NaN,Southampton,no,True
438,"Bird, Mr. Arthur",0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
456,"Wilson, Mr. Henry",0,1,male,65.0,0,0,26.5500,S,First,man,True,E,Southampton,no,True
483,"Stewart, Miss. Mary",1,3,female,63.0,0,0,9.5875,S,Third,woman,False,NaN,Southampton,yes,True
493,"Quinn, Mr. James",0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
545,"Clark, Mr. Walter",0,1,male,64.0,0,0,26.0000,S,First,man,True,NaN,Southampton,no,True
555,"White, Mr. Harold",0,1,male,62.0,0,0,26.5500,S,First,man,True,NaN,Southampton,no,True
570,"Taylor, Mr. Walter",1,2,male,62.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,yes,True
625,"Roberts, Mr. Walter",0,1,male,61.0,0,0,32.3208,S,First,man,True,D,Southampton,no,True
630,"McCarthy, Mr. Charles",1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
672,"Young, Mr. William",0,2,male,70.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
745,"Young, Mr. Robert",0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
829,"Quinn, Miss. Mary",1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
851,"Stewart, Mr. George",0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [40]:
df[condition][-1:-5:-1]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
851,"Stewart, Mr. George",0,3,male,74.0,0,0,7.775,S,Third,man,True,NaN,Southampton,no,True
829,"Quinn, Miss. Mary",1,1,female,62.0,0,0,80.000,NaN,First,woman,False,B,NaN,yes,True
745,"Young, Mr. Robert",0,1,male,70.0,1,1,71.000,S,First,man,True,B,Southampton,no,False
672,"Young, Mr. William",0,2,male,70.0,0,0,10.500,S,Second,man,True,NaN,Southampton,no,True

In [41]:
condition=(df['age']>60) & (df['sex']=='female')
df[condition]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
275,"Young, Miss. Bertha",1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
483,"Stewart, Miss. Mary",1,3,female,63.0,0,0,9.5875,S,Third,woman,False,NaN,Southampton,yes,True
829,"Quinn, Miss. Mary",1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True

In [42]:
condition=df['embark_town'].isin(['cherbourg','Queenstown'])
df[condition]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
5,"Andrews, Mr. Harold",0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
16,"Gordon, Master. Harold",0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
22,"Taylor, Miss. Alice",1,3,NaN,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
28,"Brown, Miss. Edith",1,3,NaN,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
32,"Young, Miss. Sarah",1,3,NaN,NaN,0,0,NaN,Q,Third,woman,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790,"O'Brien, Mr. John",0,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
825,"Andrews, Mr. Frank",0,3,male,NaN,0,0,6.9500,Q,Third,man,True,NaN,Queenstown,no,True
828,"Brown, Mr. Thomas",1,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,yes,True
885,"White, Mrs. Alice",0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,"Allen, Mr. Harold",0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [43]:
df.query('sex == "female" and pclass == 1 and age > 30').head()

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,"Carter, Miss. Sarah",1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,"Harris, Miss. Florence",1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,"Thompson, Miss. Mary",1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
61,"Andrews, Miss. Elizabeth",1,1,female,38.0,0,0,NaN,NaN,First,woman,False,B,NaN,yes,True
177,"Phillips, Miss. Ruth",0,1,female,50.0,0,0,28.7125,C,First,woman,False,C,Cherbourg,no,True

In [44]:
condition=(df['age'].isin(list(range(38,43)))) & (df['alive']=="yes") & (df['class']=="First") & (df['alone']==True) & (df['sex'] == "female")
df[condition]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
61,"Andrews, Miss. Elizabeth",1,1,female,38.0,0,0,NaN,NaN,First,woman,False,B,NaN,yes,True
337,"Bird, Miss. Elizabeth",1,1,female,41.0,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
380,"Harris, Miss. Bertha",1,1,female,42.0,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
609,"Allen, Miss. Hannah",1,1,female,40.0,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
716,"Walsh, Miss. Sarah",1,1,female,38.0,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True

In [45]:
df.query('sex == "female" and age >=38 and age <=42 and `class` == "First" and alone == True')

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
61,"Andrews, Miss. Elizabeth",1,1,female,38.0,0,0,NaN,NaN,First,woman,False,B,NaN,yes,True
337,"Bird, Miss. Elizabeth",1,1,female,41.0,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
380,"Harris, Miss. Bertha",1,1,female,42.0,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
609,"Allen, Miss. Hannah",1,1,female,40.0,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
716,"Walsh, Miss. Sarah",1,1,female,38.0,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True

## Selecting and Indexing

In [46]:
df['age'].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

## Filtering

In [47]:
condition=df['age'].isin(list(range(30,45)))
df[condition].head()

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,"Carter, Miss. Sarah",1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,"Harris, Miss. Florence",1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,"White, Mr. Harold",0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,"Quinn, Mr. John",0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
18,"Harris, Miss. Margaret",0,3,NaN,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [48]:
condition=df['age'].between(20,28)
df[condition]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,"Fitzgerald, Miss. Hannah",1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,"Andrews, Mrs. Alice",1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
12,"Jones, Mr. Joseph",0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
23,"Roberts, Mr. Frank",1,1,NaN,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,"Fitzgerald, Miss. Mary",0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,"Fitzgerald, Mr. William",0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,"Stewart, Mr. William",0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,"White, Mr. William",0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,"Harris, Mr. Joseph",1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [49]:
condition=df['age'].between(20,28,inclusive='both')
df[condition]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,"Fitzgerald, Miss. Hannah",1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,"Andrews, Mrs. Alice",1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
12,"Jones, Mr. Joseph",0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
23,"Roberts, Mr. Frank",1,1,NaN,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,"Fitzgerald, Miss. Mary",0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,"Fitzgerald, Mr. William",0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,"Stewart, Mr. William",0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,"White, Mr. William",0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,"Harris, Mr. Joseph",1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

- Built the new series of data which satisfy the condition

In [50]:
s=pd.Series([1,2,3,4,5,6,7,8,9])
s1=s.where(s%2==0)
s1

0    NaN
1    2.0
2    NaN
3    4.0
4    NaN
5    6.0
6    NaN
7    8.0
8    NaN
dtype: float64

In [51]:
s.where(s==3)

0    NaN
1    NaN
2    3.0
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
dtype: float64

- Mask the data which satisfy the condition

In [52]:
s.mask(s>4,other=-333)

0      1
1      2
2      3
3      4
4   -333
5   -333
6   -333
7   -333
8   -333
dtype: int64

- Bad way of masking
  - The data type are different

In [53]:
s.mask(s>4,other='*')

0    1
1    2
2    3
3    4
4    *
5    *
6    *
7    *
8    *
dtype: object

### Filtering the columns

In [54]:
df.columns

Index(['name', 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [55]:
df.filter(like='em').head()

  embarked  embark_town
0        S  Southampton
1        C    Cherbourg
2        S  Southampton
3        S  Southampton
4        S  Southampton

### Filtering the topN

In [56]:
df.nlargest(5,'fare')[['name','fare','class']]

                    name      fare  class
258    Evans, Miss. Anna  512.3292  First
679    Taylor, Mr. James  512.3292  First
737  Gordon, Mr. Charles  512.3292  First
27   Roberts, Mr. Thomas  263.0000  First
88   McCarthy, Mrs. Mary  263.0000  First

In [57]:
df.nsmallest(10,'age')

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,"Allen, Master. Arthur",1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,"Stewart, Master. Edward",1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
469,"Thompson, Miss. Ruth",1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
644,"Lewis, Miss. Helen",1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
78,"Carter, Master. Frank",1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
831,"White, Master. George",1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
305,"Gordon, Master. Edward",1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
164,"McCarthy, Master. James",0,3,male,1.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
172,"White, Miss. Edith",1,3,female,1.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
183,"Carter, Master. Walter",1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False

In [58]:
df[(df["alive"]=="yes") & (df["sex"]=="female")].nsmallest(10,"age")

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
469,"Thompson, Miss. Ruth",1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
644,"Lewis, Miss. Helen",1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
172,"White, Miss. Edith",1,3,female,1.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
381,"Gordon, Miss. Sarah",1,3,female,1.00,0,2,15.7417,C,Third,child,False,NaN,Cherbourg,yes,False
479,"Bird, Miss. Bertha",1,3,female,2.00,0,1,12.2875,S,Third,child,False,NaN,Southampton,yes,False
530,"Brown, Miss. Catherine",1,2,female,2.00,1,1,26.0000,S,Second,child,False,NaN,Southampton,yes,False
10,"Gordon, Miss. Hannah",1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
184,"Martin, Miss. Alice",1,3,female,4.00,0,2,22.0250,S,Third,child,False,NaN,Southampton,yes,False
618,"Davis, Miss. Florence",1,2,female,4.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
691,"Fitzgerald, Miss. Catherine",1,3,female,4.00,0,1,13.4167,C,Third,child,False,NaN,Cherbourg,yes,False

# Modifying DataFrame

### Deleting the columns

In [59]:
df.drop(columns=['deck','embark_town']).head()

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,no,False
1,"Carter, Miss. Sarah",1,1,female,38.0,1,0,71.2833,C,First,woman,False,yes,False
2,"Fitzgerald, Miss. Hannah",1,3,female,26.0,0,0,7.9250,S,Third,woman,False,yes,True
3,"Harris, Miss. Florence",1,1,female,35.0,1,0,53.1000,S,First,woman,False,yes,False
4,"White, Mr. Harold",0,3,male,35.0,0,0,8.0500,S,Third,man,True,no,True

In [60]:
df1=df.drop(columns=['deck','embark_town']).head()
df1

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,no,False
1,"Carter, Miss. Sarah",1,1,female,38.0,1,0,71.2833,C,First,woman,False,yes,False
2,"Fitzgerald, Miss. Hannah",1,3,female,26.0,0,0,7.9250,S,Third,woman,False,yes,True
3,"Harris, Miss. Florence",1,1,female,35.0,1,0,53.1000,S,First,woman,False,yes,False
4,"White, Mr. Harold",0,3,male,35.0,0,0,8.0500,S,Third,man,True,no,True

In [61]:
df.drop(columns=['deck','embark_town'],inplace=True)
df.head()

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,no,False
1,"Carter, Miss. Sarah",1,1,female,38.0,1,0,71.2833,C,First,woman,False,yes,False
2,"Fitzgerald, Miss. Hannah",1,3,female,26.0,0,0,7.9250,S,Third,woman,False,yes,True
3,"Harris, Miss. Florence",1,1,female,35.0,1,0,53.1000,S,First,woman,False,yes,False
4,"White, Mr. Harold",0,3,male,35.0,0,0,8.0500,S,Third,man,True,no,True

### Deleting the rows

In [62]:
df.drop(index=[1,2,3,4],inplace=True)

In [63]:
df.drop(index=[1,2,3,4],inplace=True)

KeyError: '[1, 2, 3, 4] not found in axis'

## Replacing value

In [ ]:
df["sex"].replace(to_replace={"male":"M","female":"F"})

## Finding missing value

In [ ]:
df.isna().sum()

## Filling a missing value

In [ ]:
df['age'].value_counts()

### Filling with constant value

In [ ]:
df.fillna(value={'age':1000},inplace=True)

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,no,False
5,"Andrews, Mr. Harold",0,3,male,1000.0,0,0,8.4583,Q,Third,man,True,no,True
6,"Harris, Mr. Robert",0,1,male,54.0,0,0,51.8625,S,First,man,True,no,True
7,"Nelson, Master. Charles",0,3,male,2.0,3,1,21.0750,S,Third,child,False,no,False
8,"Andrews, Mrs. Alice",1,3,female,27.0,0,2,11.1333,S,Third,woman,False,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,"White, Mr. William",0,2,male,27.0,0,0,13.0000,S,Second,man,True,no,True
887,"Roberts, Miss. Edith",1,1,female,19.0,0,0,30.0000,S,First,woman,False,yes,True
888,"White, Mrs. Hannah",0,3,female,1000.0,1,2,23.4500,S,Third,woman,False,no,False
889,"Harris, Mr. Joseph",1,1,male,26.0,0,0,30.0000,C,First,man,True,yes,True
890,"Allen, Mr. Harold",0,3,male,32.0,0,0,7.7500,Q,Third,man,True,no,True

In [ ]:
df[df['age']==1000]

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,alive,alone
5,"Andrews, Mr. Harold",0,3,male,1000.0,0,0,8.4583,Q,Third,man,True,no,True
17,"Nelson, Mr. William",1,2,male,1000.0,0,0,13.0000,S,Second,man,True,yes,True
19,"Clark, Miss. Emily",1,3,female,1000.0,0,0,7.2250,C,Third,woman,False,yes,True
26,"Taylor, Mr. Harold",0,3,male,1000.0,0,0,7.2250,C,Third,man,True,no,True
28,"Brown, Miss. Edith",1,3,female,1000.0,0,0,7.8792,Q,Third,woman,False,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,"Quinn, Mr. George",0,3,male,1000.0,0,0,7.2292,C,Third,man,True,no,True
863,"Allen, Mrs. Sarah",0,3,female,1000.0,8,2,69.5500,S,Third,woman,False,no,False
868,"Roberts, Mr. William",0,3,male,1000.0,0,0,9.5000,S,Third,man,True,no,True
878,"Brown, Mr. Joseph",0,3,male,1000.0,0,0,7.8958,S,Third,man,True,no,True
888,"White, Mrs. Hannah",0,3,female,1000.0,1,2,23.4500,S,Third,woman,False,no,False

In [64]:
df=pd.read_csv("titanic.csv")
df.isna().sum()

name             0
survived         0
pclass           0
sex             39
age            177
sibsp            0
parch            0
fare            39
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df['fare'].mean()

np.float64(32.36500786384976)

In [ ]:
df['fare'].median()

np.float64(14.4542)

In [ ]:
df_filled=df['fare'].fillna(df['fare'].median())
df_filled

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: fare, Length: 891, dtype: float64

In [ ]:
df_filled[df_filled==14.4542]

31     14.4542
32     14.4542
33     14.4542
34     14.4542
35     14.4542
36     14.4542
37     14.4542
38     14.4542
39     14.4542
40     14.4542
41     14.4542
42     14.4542
43     14.4542
44     14.4542
45     14.4542
46     14.4542
47     14.4542
48     14.4542
49     14.4542
50     14.4542
51     14.4542
52     14.4542
53     14.4542
54     14.4542
55     14.4542
56     14.4542
57     14.4542
58     14.4542
59     14.4542
60     14.4542
61     14.4542
62     14.4542
63     14.4542
64     14.4542
65     14.4542
66     14.4542
67     14.4542
68     14.4542
69     14.4542
73     14.4542
111    14.4542
240    14.4542
362    14.4542
620    14.4542
702    14.4542
830    14.4542
Name: fare, dtype: float64

In [ ]:
df.head()

,name,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,"Kelly, Mr. Patrick",0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,"Carter, Miss. Sarah",1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,"Fitzgerald, Miss. Hannah",1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,"Harris, Miss. Florence",1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,"White, Mr. Harold",0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [65]:
df['deck'].fillna(value=df['deck'].mode()[0],inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_4956\2585648526.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['deck'].fillna(value=df['deck'].mode()[0],inplace=True)

0      C
1      C
2      C
3      C
4      C
      ..
886    C
887    B
888    C
889    C
890    C
Name: deck, Length: 891, dtype: str

In [66]:
df['deck'].value_counts()

deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64

In [ ]:
df['deck']=df['deck'].fillna(value=df['deck'].mode()[0])

In [ ]:
df['deck'].value_counts()

deck
C    747
B     47
D     33
E     32
A     15
F     13
G      4
Name: count, dtype: int64

# DateTime Operations - the `.dt` accessors

In [ ]:
dates=pd.date_range(start="2024-01-01",periods=10,freq="D")
print(dates)

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[us]', freq='D')

In [76]:
dates=pd.date_range(start="2024-01-01",end="2024-01-05",periods=20).normalize()
ts=pd.DataFrame({'date': dates, 'value': np.random.randn(20).cumsum()})
ts

         date     value
0  2024-01-01  0.696761
1  2024-01-01 -0.970434
2  2024-01-01 -0.672486
3  2024-01-01  0.992033
4  2024-01-01  1.283304
5  2024-01-02  1.634271
6  2024-01-02  2.332601
7  2024-01-02  2.747364
8  2024-01-02  3.325661
9  2024-01-02  2.192146
10 2024-01-03  2.039480
11 2024-01-03  2.916044
12 2024-01-03  2.871677
13 2024-01-03  3.092541
14 2024-01-03  2.575842
15 2024-01-04  2.165474
16 2024-01-04  1.112715
17 2024-01-04  1.119437
18 2024-01-04  1.649988
19 2024-01-05  0.360778

## Operation in the DatetimeIndex

In [78]:
ts['year']      = ts['date'].dt.year
ts['month']     = ts['date'].dt.month
ts['day']       = ts['date'].dt.day
ts['dayofweek'] = ts['date'].dt.dayofweek    # Monday = 0
ts['day_name']  = ts['date'].dt.day_name()
ts.head()

        date     value  year  month  day  dayofweek day_name
0 2024-01-01  0.696761  2024      1    1          0   Monday
1 2024-01-01 -0.970434  2024      1    1          0   Monday
2 2024-01-01 -0.672486  2024      1    1          0   Monday
3 2024-01-01  0.992033  2024      1    1          0   Monday
4 2024-01-01  1.283304  2024      1    1          0   Monday

In [82]:
dates=pd.date_range(start="2026-06-27",periods=10,freq="D").normalize()
ts=pd.DataFrame({'date': dates, 'value': np.random.randn(10).cumsum()})
ts

        date     value
0 2026-06-27  0.384992
1 2026-06-28  2.100421
2 2026-06-29  0.604820
3 2026-06-30  0.235115
4 2026-07-01  1.352279
5 2026-07-02  2.086828
6 2026-07-03  2.660621
7 2026-07-04  3.681998
8 2026-07-05  3.911997
9 2026-07-06  4.110677

In [87]:
dates=pd.date_range(start="2025-06-27",periods=30,freq="ME").normalize()
dates

DatetimeIndex(['2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30',
               '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31',
               '2026-02-28', '2026-03-31', '2026-04-30', '2026-05-31',
               '2026-06-30', '2026-07-31', '2026-08-31', '2026-09-30',
               '2026-10-31', '2026-11-30', '2026-12-31', '2027-01-31',
               '2027-02-28', '2027-03-31', '2027-04-30', '2027-05-31',
               '2027-06-30', '2027-07-31', '2027-08-31', '2027-09-30',
               '2027-10-31', '2027-11-30'],
              dtype='datetime64[us]', freq='ME')

In [88]:
dates.day_name()

Index(['Monday', 'Thursday', 'Sunday', 'Tuesday', 'Friday', 'Sunday',
       'Wednesday', 'Saturday', 'Saturday', 'Tuesday', 'Thursday', 'Sunday',
       'Tuesday', 'Friday', 'Monday', 'Wednesday', 'Saturday', 'Monday',
       'Thursday', 'Sunday', 'Sunday', 'Wednesday', 'Friday', 'Monday',
       'Wednesday', 'Saturday', 'Tuesday', 'Thursday', 'Sunday', 'Tuesday'],
      dtype='str')

In [100]:
li=df.groupby(['class','sex'])['fare'].sum()
li

class   sex
First   female    9672.5750
        male      7532.5209
Second  female    1532.4000
        male      2069.6125
Third   female    2139.6918
        male      4141.2490
Name: fare, dtype: float64

In [117]:
df=pd.read_excel('sales.xlsx')
df

     day  price cst_prof
0    sun    300        H
1    mon     40        L
2   tues    200        L
3    sun    450        H
4   thur    222        H
5    fri    456        L
6    sat   1234        L
7    mon    499        L
8   tues    234        H
9    fri    500        H
10   sat    403        H

In [118]:
obj=df.groupby('day')['price']
for i,j in obj:
    print(i)
    print(j)

fri
5    456
9    500
Name: price, dtype: int64
mon
1     40
7    499
Name: price, dtype: int64
sat
6     1234
10     403
Name: price, dtype: int64
sun
0    300
3    450
Name: price, dtype: int64
thur
4    222
Name: price, dtype: int64
tues
2    200
8    234
Name: price, dtype: int64

In [119]:
df.groupby('day')['price'].max()

day
fri      500
mon      499
sat     1234
sun      450
thur     222
tues     234
Name: price, dtype: int64

In [120]:
df.groupby('day')['price'].mean()

day
fri     478.0
mon     269.5
sat     818.5
sun     375.0
thur    222.0
tues    217.0
Name: price, dtype: float64

In [114]:
df

     day  price
0    sun    300
1    mon     40
2   tues    200
3    sun    450
4   thur    222
5    fri    456
6    sat   1234
7    mon    499
8   tues    234
9    fri    500
10   sat    403

In [121]:
def mod(x):
    return x.mode()[0]

In [122]:
df.groupby('day')['price'].agg(['mean','median',mod,'std','min','max','count'])

       mean  median  mod         std  min   max  count
day
fri   478.0   478.0  456   31.112698  456   500      2
mon   269.5   269.5   40  324.562013   40   499      2
sat   818.5   818.5  403  587.605735  403  1234      2
sun   375.0   375.0  300  106.066017  300   450      2
thur  222.0   222.0  222         NaN  222   222      1
tues  217.0   217.0  200   24.041631  200   234      2

In [125]:
df.groupby(['day','cst_prof'])['price'].agg(['mean','median',mod,'std','min','max','count'])

                 mean  median   mod         std   min   max  count
day  cst_prof
fri  H          500.0   500.0   500         NaN   500   500      1
     L          456.0   456.0   456         NaN   456   456      1
mon  L          269.5   269.5    40  324.562013    40   499      2
sat  H          403.0   403.0   403         NaN   403   403      1
     L         1234.0  1234.0  1234         NaN  1234  1234      1
sun  H          375.0   375.0   300  106.066017   300   450      2
thur H          222.0   222.0   222         NaN   222   222      1
tues H          234.0   234.0   234         NaN   234   234      1
     L          200.0   200.0   200         NaN   200   200      1